version: '3'

services:
  backend:
    build: ./backend
    command: ./manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - ./backend:/home/backend
    depends_on:
      - db
  db:
    image: postgres
